export const MESSAGE_VERSION = '1.0';

export const WEBSOCKET_PATHS = {
  BOARD: '/ws/board',
  CLIENT: '/ws/client',
} as const;

export const BLE_UUID = {
  SERVICE: '6e400001-b5a3-f393-e0a9-e50e24dcca9e',
  CHAR_TX: '6e400002-b5a3-f393-e0a9-e50e24dcca9e',
  CHAR_RX: '6e400003-b5a3-f393-e0a9-e50e24dcca9e',
} as const;

export const HEARTBEAT_INTERVAL_MS = 30000;
export const HEARTBEAT_TIMEOUT_MS = 60000;
export const WIFI_RECONNECT_INTERVAL_MS = 3000;
export const WS_RECONNECT_INTERVAL_MS = 5000;

export const DEFAULT_SESSION_DURATION = 3600;

export const ERROR_CODES = {
  BOARD_NOT_FOUND: 'BOARD_NOT_FOUND',
  CLIENT_NOT_FOUND: 'CLIENT_NOT_FOUND',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  BOARD_NOT_IDLE: 'BOARD_NOT_IDLE',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  INVALID_MESSAGE: 'INVALID_MESSAGE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;
